site:
    title: 沉稳,不乏可爱
    introduce: cwen's code、note、life and anything 
    limit: 1
    theme: themes/default
    url: http://liujia.mom
    comment: cwengo
    github: https://github.com/cwen-coder
    facebook: 
    twitter: 
build:
    port: 3000
    copy: 
        - "sdsdsd"
    publish: fdfdf

